name = "Picklemon"
author = "Mason"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e7c283a4411330b6009b85c59c3bd6309bf16a5ffc83b37daceeb5943308eb7"

[versions]
forge = "36.2.41"
minecraft = "1.16.5"
