name = "Picklemon"
author = "Mason"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72bd10b9d7bbec955290d5c0bf0103514b1ce39ac3d7117ab1f6aaeb118be485"

[versions]
forge = "36.2.41"
minecraft = "1.16.5"
