name = "Picklemon"
author = "Mason"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1a17237f718b90b6b721df55ad18e38de4bcd832631d18fce3a98508cc9bf94"

[versions]
forge = "36.2.41"
minecraft = "1.16.5"
