name = "Packwiz Pixelmon"
author = "Shrekshellraiser"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3129492e40f2f798a9d96555d83b3bfe0f3c6b05c9a2050ecbd259274fef786d"

[versions]
forge = "48.1.0"
minecraft = "1.20.2"
