name = "Picklemon"
author = "Mason"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e89e0ca3ef711158115f2980efffce910f1319334ad0a20f77431df61478d6e"

[versions]
forge = "36.2.41"
minecraft = "1.16.5"
