name = "Picklemon"
author = "Mason"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "685e2dd8670dbb9ad16052eb6cc3778eabc727f6e76a8c8b146fcc401abac16f"

[versions]
forge = "36.2.41"
minecraft = "1.16.5"
