name = "Packwiz Pixelmon"
author = "Shrekshellraiser"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "179fc64ddb71ac85c7583956646e11b4557e7b767d26fdfb521724c2aea68650"

[versions]
forge = "48.1.0"
minecraft = "1.20.2"
