# © PixelmonMod 2013-2023

allow-breeding: true
allow-ditto-ditto-breeding: true
allow-random-breeding-eggs-to-be-legendary: true
allow-random-breeding-eggs-to-be-mythic: true
allow-random-breeding-eggs-to-be-ultrabeast: true
allow-cross-region-hidden-ability-inheritance: true
oval-charm-multiplier: 0.5
steps-per-egg-cycle: 255
default-day-care-amount: 3
